### ISSUE TITLE
Obviate requiring `--impure`

### ISSUE THREAD

**Issue by srid** [cardano-system/cardano-system#1]
There ought to be a way to do it.

cf. https://github.com/srid/nixos-config/pull/12

**Comment by locallycompact** [comment]
I think this is an upstream problem with cardano-node. I am using this branch

https://github.com/cardano-system/cardano-system/commit/97b59721c1f087d21f18658d6b8482f9827d1fd5

and in my system:

```
            cardano-system.nixosModules.cardano-node
            cardano-system.nixosModules.cardano-system
            {
              services.cardano-system.enable = true;
            }
```

Still get the error without --impure.

**Comment by nixinator** [comment]
for completeness this is what i get.

`
error: attribute 'currentSystem' missing

       at /nix/store/6k0ifa8p59k7snfaxiz4sgqqfvad412p-source/pkgs/top-level/impure.nix:18:43:

           17|   # (build, in GNU Autotools parlance) platform.
           18|   localSystem ? { system = args.system or builtins.currentSystem; }
             |                                           ^
           19|
(use '--show-trace' to show detailed location information)
`

currentSystem is impure, so this error makes sense, somewhere within the import flakes/code there is this impurity...it needs to be fixed upstream.


running with --impure gives.

`
error: builder for '/nix/store/83682lkyck8v1zykdpgs2q428p2yvnff-source.drv' failed with exit code 1;
       last 8 log lines:
       >
       > trying https://api.github.com/repos/numtide/flake-utils/tarball/3cecb5b042f7f209c56ffd8371b2711a290ec797
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > 100  7472  100  7472    0     0  18510      0 --:--:-- --:--:-- --:--:-- 18510
       > unpacking source archive /build/3cecb5b042f7f209c56ffd8371b2711a290ec797
       > do not know how to unpack source archive /build/3cecb5b042f7f209c56ffd8371b2711a290ec797
       For full logs, run 'nix log /nix/store/83682lkyck8v1zykdpgs2q428p2yvnff-source.drv'.
(use '--show-trace' to show detailed location information)
`

**Comment by MatthewCroughan** [comment]
Closed by https://github.com/cardano-system/cardano-system/pull/4
